robots:
  - name: robot1
    x_pose: '0.0'
    y_pose: '0.0'
    z_pose: '0.8'
    enabled: true
  # - name: robot2
  #   x_pose: '-2.0'
  #   y_pose: '0.0'
  #   z_pose: '0.8'
  # - name: robot3
  #   x_pose: '0.0'
  #   y_pose: '-2.0'
  #   z_pose: '0.8'
  # - name: robot4
  #   x_pose: '-2.0'
  #   y_pose: '-2.0'
  #   z_pose: '0.8'
  # add more robots if you need, but unable multi robots in cyclonedds config file